"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Story = { id:number; title:string; subtitle:string; titleEn:string; subtitleEn:string; status:"Needs review"|"Approved"|"Ready"; duration:string; sources:number; progress:number; color:string };
const initialStories:Story[]=[
 {id:1,title:"حضرت ایوبؑ کا صبر",subtitle:"آزمائش میں ثابت قدم ایمان کی کہانی",titleEn:"The Patience of Prophet Ayyub",subtitleEn:"A story of faith through hardship",status:"Needs review",duration:"3:42",sources:4,progress:72,color:"sand"},
 {id:2,title:"حضرت یوسفؑ اور معافی کی طاقت",subtitle:"اختیار کے وقت رحم کا انتخاب",titleEn:"Prophet Yusuf and the Power of Forgiveness",subtitleEn:"Choosing mercy when you have power",status:"Approved",duration:"4:18",sources:6,progress:100,color:"blue"},
 {id:3,title:"حضرت عمرؓ کا عدل",subtitle:"ایک رہنما جو اپنا احتساب کرتا تھا",titleEn:"The Justice of Umar ibn Al-Khattab",subtitleEn:"A leader who held himself accountable",status:"Ready",duration:"3:56",sources:5,progress:100,color:"green"}
];
const storyText=`حضرت ایوب علیہ السلام کو صحت، خاندان اور رزق کی نعمتیں عطا ہوئی تھیں۔ پھر انہیں ایک طویل آزمائش کا سامنا کرنا پڑا، لیکن اللہ پر ان کا بھروسا کبھی کم نہ ہوا۔ انہوں نے عاجزی سے اپنے رب کو پکارا کہ مجھے تکلیف پہنچی ہے اور تو سب رحم کرنے والوں سے بڑھ کر رحم کرنے والا ہے۔ اللہ تعالیٰ نے ان کی دعا قبول فرمائی۔ یہ واقعہ ہمیں سکھاتا ہے کہ صبر، تکلیف کے باوجود ایمان قائم رکھنے، اللہ سے مدد مانگنے اور اس کی حکمت پر بھروسا کرنے کا نام ہے۔`;
const storyTextEn=`Prophet Ayyub, peace be upon him, was blessed with health, family, and provision. Then he was tested with a long period of hardship, but his trust in Allah never left him. He called upon his Lord with humility. Allah answered his prayer. His story teaches us that patience means carrying pain while keeping faith, asking Allah for help, and trusting His wisdom.`;
const steps={en:["Research","Verify","Script","Voice","Video","YouTube"],ur:["تحقیق","تصدیق","اسکرپٹ","آواز","ویڈیو","یوٹیوب"]};

export default function Home(){
 const [stories,setStories]=useState(initialStories),[selectedId,setSelectedId]=useState(1),[tab,setTab]=useState("stories"),[playingLanguage,setPlayingLanguage]=useState<"ur"|"en"|null>(null),[notice,setNotice]=useState(""),[generating,setGenerating]=useState(false),[query,setQuery]=useState("");
 const [scheduleOpen,setScheduleOpen]=useState(false),[scheduleEnabled,setScheduleEnabled]=useState(true),[frequency,setFrequency]=useState("Daily"),[scheduleTime,setScheduleTime]=useState("10:00"),[timezone,setTimezone]=useState("Asia/Dubai"),[days,setDays]=useState(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]);
 const [language,setLanguage]=useState<"ur"|"en">("en");
 const [seoOpen,setSeoOpen]=useState(false),[seoVariant,setSeoVariant]=useState(0);
 const audioRef=useRef<HTMLAudioElement|null>(null),audioUrlRef=useRef<string|null>(null);
 const selected=stories.find(s=>s.id===selectedId)??stories[0];
 const filtered=useMemo(()=>stories.filter(s=>(language==="ur"?s.title:s.titleEn).toLowerCase().includes(query.toLowerCase())),[stories,query,language]);
 const storyTitle=(s:Story)=>language==="ur"?s.title:s.titleEn;
 const storySubtitle=(s:Story)=>language==="ur"?s.subtitle:s.subtitleEn;
 const t=(english:string,urdu:string)=>language==="en"?english:urdu;
 const navItems=[{id:"overview",icon:"⌂",en:"Overview",ur:"جائزہ"},{id:"stories",icon:"▤",en:"Story queue",ur:"کہانیوں کی فہرست"},{id:"sources",icon:"◇",en:"Source library",ur:"مآخذ کی لائبریری"},{id:"studio",icon:"▶",en:"Video studio",ur:"ویڈیو اسٹوڈیو"},{id:"publishing",icon:"↗",en:"Publishing",ur:"اشاعت"}];
 const youtubePack=useMemo(()=>{const title=language==="ur"?`${storyTitle(selected)} | ایمان بدل دینے والی سچی اسلامی کہانی`:`${storyTitle(selected)} | A Powerful Islamic Story of Faith`;const alt=language==="ur"?`${storyTitle(selected)} — صبر اور توکل کا سبق`:`What ${storyTitle(selected)} Teaches Us About Faith`;const description=language==="ur"?`${storySubtitle(selected)}۔ اس مختصر اسلامی کہانی میں معتبر مآخذ کی روشنی میں ایمان، صبر اور اللہ پر توکل کا سبق جانیں۔\n\nحوالہ: قرآن 21:83–84۔ اشاعت سے پہلے تمام مذہبی دعووں کا انسانی جائزہ ضروری ہے۔\n\n#اسلامی_کہانیاں #قرآن #صبر #اردو`:`${storySubtitle(selected)}. Discover a timeless lesson about faith, patience, and trust in Allah through this carefully sourced Islamic story.\n\nReference: Qur’an 21:83–84. All religious claims require human review before publication.\n\n#IslamicStories #Quran #Sabr #MuslimReminder`;const tags=language==="ur"?["اسلامی کہانیاں","اردو اسلامی ویڈیو","حضرت ایوب","صبر","اللہ پر توکل","قرآنی واقعات","مسلم بچوں کی کہانیاں"]:["islamic stories","prophet stories","Prophet Ayyub","patience in Islam","trust in Allah","Quran stories","Muslim reminder"];return{title:seoVariant%2?alt:title,description,tags:tags.join(", ")}},[selected,language,seoVariant]);
 useEffect(()=>{const saved=localStorage.getItem("noor-schedule");if(saved){try{const s=JSON.parse(saved);setScheduleEnabled(s.enabled);setFrequency(s.frequency);setScheduleTime(s.time);setTimezone(s.timezone);setDays(s.days)}catch{}}return()=>{audioRef.current?.pause();if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);window.speechSynthesis?.cancel()}},[]);
 async function speak(targetLanguage:"ur"|"en"){
  if(playingLanguage){audioRef.current?.pause();audioRef.current=null;setPlayingLanguage(null);if(playingLanguage===targetLanguage)return}
  const spokenTitle=targetLanguage==="ur"?selected.title:selected.titleEn;
  setPlayingLanguage(targetLanguage);
  try{
   const response=await fetch("/api/speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language:targetLanguage,text:`${spokenTitle}. ${targetLanguage==="ur"?storyText:storyTextEn}`})});
   if(!response.ok)throw new Error("Speech request failed");
   if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);
   const url=URL.createObjectURL(await response.blob());audioUrlRef.current=url;
   const audio=new Audio(url);audioRef.current=audio;
   audio.onended=()=>setPlayingLanguage(null);audio.onerror=()=>{setPlayingLanguage(null);setNotice(targetLanguage==="ur"?"اردو آواز چل نہیں سکی۔":"English audio could not be played.")};
   await audio.play();
  }catch{setPlayingLanguage(null);setNotice(targetLanguage==="ur"?"اردو آواز کی سروس دستیاب نہیں۔ براہ کرم دوبارہ کوشش کریں۔":"Speech service is unavailable. Please try again.")}
 }
 function approve(){setStories(c=>c.map(s=>s.id===selected.id?{...s,status:"Approved",progress:100}:s));setNotice(language==="ur"?"کہانی منظور ہو گئی۔ اردو ویڈیو بنانے کے لیے فہرست میں شامل کر دی گئی ہے۔":"Story approved and added to the English video queue.")}
 function generate(){setGenerating(true);setNotice(language==="ur"?"معتبر اسلامی مآخذ تلاش کر کے اردو مسودہ تیار کیا جا رہا ہے…":"Searching authentic Islamic sources and preparing an English draft…");setTimeout(()=>{const s:Story={id:Date.now(),title:"فرعون کے سامنے حضرت موسیٰؑ کی جرأت",subtitle:"اللہ پر بھروسا کرتے ہوئے حق بات کہنا",titleEn:"The Courage of Musa Before Pharaoh",subtitleEn:"Speaking truth with trust in Allah",status:"Needs review",duration:"4:05",sources:5,progress:68,color:"purple"};setStories(c=>[s,...c]);setSelectedId(s.id);setGenerating(false);setNotice(language==="ur"?"نیا اردو مسودہ آپ کے جائزے کے لیے تیار ہے۔":"A new English draft is ready for your review.")},1200)}
 function saveSchedule(){localStorage.setItem("noor-schedule",JSON.stringify({enabled:scheduleEnabled,frequency,time:scheduleTime,timezone,days}));setScheduleOpen(false);setNotice(scheduleEnabled?t(`Schedule saved. The next draft will be created at ${scheduleTime}.`,`شیڈول محفوظ ہو گیا۔ اگلا مسودہ ${scheduleTime} بجے تیار ہوگا۔`):t("Automatic story creation is paused.","خودکار کہانی بنانا روک دیا گیا ہے۔"))}
 function toggleDay(day:string){setDays(current=>current.includes(day)?current.filter(d=>d!==day):[...current,day])}
 function copyText(value:string,label:string){navigator.clipboard?.writeText(value);setNotice(language==="ur"?`${label} کاپی ہو گیا۔`:`${label} copied.`)}
 return <main className={`app-shell ${language==="ur"?"urdu":"english"}`} dir={language==="ur"?"rtl":"ltr"} lang={language}>
  <aside className="sidebar"><div className="brand"><span className="brand-mark">ن</span><div><strong>{t("Noor Studio","نور اسٹوڈیو")}</strong><small>{t("Stories with purpose","بامقصد کہانیاں")}</small></div></div>
   <nav aria-label={t("Main navigation","مرکزی مینو")}>{navItems.map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><span>{item.icon}</span>{language==="en"?item.en:item.ur}{item.id==="stories"&&<b>{stories.filter(s=>s.status==="Needs review").length}</b>}</button>)}</nav>
   <div className="sidebar-bottom"><button onClick={()=>setNotice(t("Settings are ready for API keys and channel preferences.","API keys اور چینل کی ترجیحات کے لیے ترتیبات تیار ہیں۔"))}><span>⚙</span>{t("Settings","ترتیبات")}</button><div className="profile"><span>MA</span><div><strong>{t("Mohamed Ali","محمد علی")}</strong><small>{t("Channel owner","چینل کا مالک")}</small></div><i>⌄</i></div></div>
  </aside>
  <section className="workspace">
   <header><div><p>{t("ENGLISH CHANNEL","اردو چینل")}</p><h1>{t("Your story studio","آپ کا کہانی اسٹوڈیو")}</h1><span>{t("Create meaningful stories grounded in authentic sources.","معتبر مآخذ پر مبنی بامقصد کہانیاں بنائیں۔")}</span></div><div className="header-actions"><div className="language-switch" dir="ltr" aria-label="Content language"><button className={language==="ur"?"active":""} onClick={()=>{setLanguage("ur");setQuery("")}}>اردو</button><button className={language==="en"?"active":""} onClick={()=>{setLanguage("en");setQuery("")}}>English</button></div><button className="icon-btn" aria-label={t("Notifications","اطلاعات")}>♢<i/></button><button className="primary" onClick={generate} disabled={generating}><span>＋</span>{generating?t("Researching…","تحقیق جاری ہے…"):t("Create story","نئی کہانی بنائیں")}</button></div></header>
   {notice&&<div className="notice" role="status"><span>✓</span>{notice}<button onClick={()=>setNotice("")}>×</button></div>}
   <section className="stats-grid">
    <article><div className="stat-icon peach">✦</div><div><p>{t("Stories this month","اس ماہ کی کہانیاں")}</p><strong>12</strong><small><em>↑ 20%</em> {t("from last month","پچھلے ماہ سے زیادہ")}</small></div></article>
    <article><div className="stat-icon mint">✓</div><div><p>{t("Awaiting your review","آپ کے جائزے کی منتظر")}</p><strong>{stories.filter(s=>s.status==="Needs review").length}</strong><small>{t("Accuracy check needed","درستگی کی جانچ ضروری ہے")}</small></div></article>
    <article><div className="stat-icon lilac">▶</div><div><p>{t("Videos published","شائع شدہ ویڈیوز")}</p><strong>8</strong><small>{t("4 scheduled this week","اس ہفتے 4 شیڈول ہیں")}</small></div></article>
    <article><div className="stat-icon sky">◴</div><div><p>{t("Time saved","بچایا گیا وقت")}</p><strong>{t("18.5h","18.5 گھنٹے")}</strong><small>{t("This month","اس ماہ")}</small></div></article>
   </section>
   <section className="content-grid"><div className="queue-card">
    <div className="section-title"><div><h2>{language==="ur"?"کہانیوں کی فہرست":"Story queue"}</h2><p>{language==="ur"?"کچھ بھی بنانے سے پہلے تحقیق کا جائزہ لیں۔":"Review the research before production."}</p></div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={language==="ur"?"کہانی تلاش کریں":"Search stories"}/></label></div>
    <div className="story-list" dir={language==="ur"?"rtl":"ltr"}>{filtered.map(s=><button key={s.id} className={`story-row ${selected.id===s.id?"selected":""}`} onClick={()=>setSelectedId(s.id)}><span className={`story-art ${s.color}`}><i>☾</i></span><span className="story-main"><strong>{storyTitle(s)}</strong><small>{storySubtitle(s)}</small><span className="meta">◷ {s.duration}　◇ {s.sources} {language==="ur"?"تصدیق شدہ مآخذ":"verified sources"}</span></span><span className="story-state"><i className={s.status.replace(" ","-").toLowerCase()}>{language==="ur"?(s.status==="Needs review"?"جائزہ درکار":s.status==="Approved"?"منظور شدہ":"تیار"):s.status}</i><small>{s.progress}% {language==="ur"?"مکمل":"complete"}</small><span className="progress"><b style={{width:`${s.progress}%`}}/></span></span><span className="chevron">‹</span></button>)}</div>
    <button className="view-all" onClick={()=>setQuery("")}>{t("View all stories","تمام کہانیاں دیکھیں")} <span>{t("→","←")}</span></button>
   </div><aside className="review-card" dir={language==="ur"?"rtl":"ltr"}><div className="review-head"><span>{language==="ur"?"جائزہ ضروری ہے":"REVIEW REQUIRED"}</span><small>{language==="ur"?"انسانی منظوری درستگی کی حفاظت کرتی ہے":"Human approval protects accuracy"}</small></div><div className={`review-art ${selected.color}`}><span>☾</span><i>✦</i><b>✦</b></div><div className="review-body"><h2>{storyTitle(selected)}</h2><p>{storySubtitle(selected)}</p>
    <div className="voice-options"><button className={`listen ${playingLanguage==="ur"?"playing":""}`} onClick={()=>speak("ur")}><span>{playingLanguage==="ur"?"Ⅱ":"▶"}</span><strong>{playingLanguage==="ur"?"سننا بند کریں":"اردو میں سنیں"}</strong><small>Urdu · ur-PK</small></button><button className={`listen ${playingLanguage==="en"?"playing":""}`} onClick={()=>speak("en")}><span>{playingLanguage==="en"?"Ⅱ":"▶"}</span><strong>{playingLanguage==="en"?"Stop listening":"Listen in English"}</strong><small>English · en-US</small></button></div>
    <div className="source-check"><div className="source-title"><span>✓</span><div><strong>{language==="ur"?"مآخذ کی تصدیق":"Source verification"}</strong><small>{selected.sources} {language==="ur"?"حوالوں کی جانچ مکمل":"references checked"}</small></div><button onClick={()=>setNotice(language==="ur"?"مآخذ: قرآن 21:83–84، تفسیر ابن کثیر اور تقابلی تشریح۔":"Sources: Qur’an 21:83–84, Tafsir Ibn Kathir, and cross-checked commentary.")}>{language==="ur"?"مآخذ دیکھیں":"View sources"}</button></div><ul><li><span>{language==="ur"?"قرآن":"Qur’an"}</span><b>21:83–84</b><i>{language==="ur"?"تصدیق شدہ":"Verified"}</i></li><li><span>{language==="ur"?"ترجمہ":"Translation"}</span><b>{language==="ur"?"صحیح انٹرنیشنل":"Sahih International"}</b><i>{language==="ur"?"تصدیق شدہ":"Verified"}</i></li><li><span>{language==="ur"?"دعوے":"Claims"}</span><b>{language==="ur"?"کوئی غیر مستند تفصیل نہیں":"No unsupported details"}</b><i>{language==="ur"?"جانچ مکمل":"Checked"}</i></li></ul></div>
    <button className="approve" onClick={approve} disabled={selected.status!=="Needs review"}>✓ {selected.status==="Needs review"?(language==="ur"?"منظور کریں اور ویڈیو بنائیں":"Approve & create video"):(language==="ur"?"منظور شدہ":"Approved")}</button><button className="seo-button" onClick={()=>setSeoOpen(true)}>↗ {language==="ur"?"یوٹیوب عنوان، تفصیل اور ٹیگز":"YouTube title, description & tags"}</button><button className="edit" onClick={()=>setNotice(language==="ur"?"کہانی کا ایڈیٹر کھل گیا ہے۔ منظوری سے پہلے آپ ہر سطر تبدیل کر سکتے ہیں۔":"Story editor opened. You can revise any line before approval.")}>{language==="ur"?"پہلے کہانی میں ترمیم کریں":"Edit story first"}</button>
   </div></aside></section>
   <section className="pipeline"><div><h2>{t("Today’s automation","آج کی خودکاری")}</h2><p>{t("The bot pauses at verification and waits for you.","بوٹ تصدیق پر رک کر آپ کی منظوری کا انتظار کرتا ہے۔")}</p></div><div className="steps">{steps[language].map((s,i)=><div key={s} className={i<2?"done":i===2?"current":""}><span>{i<2?"✓":i+1}</span><small>{s}</small>{i<steps[language].length-1&&<i/>}</div>)}</div><button className={scheduleEnabled?"schedule-on":""} onClick={()=>setScheduleOpen(true)}>{scheduleEnabled?`${frequency==="Daily"?t("Daily","روزانہ"):frequency==="Weekly"?t("Weekly","ہفتہ وار"):t("Custom days","منتخب دن")} · ${scheduleTime}`:t("Schedule off","شیڈول بند")}　⌄</button></section>
   {scheduleOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setScheduleOpen(false)}}><section className="schedule-modal" dir={language==="ur"?"rtl":"ltr"} role="dialog" aria-modal="true" aria-labelledby="schedule-title">
    <button className="modal-close" aria-label={t("Close schedule","شیڈول بند کریں")} onClick={()=>setScheduleOpen(false)}>×</button><span className="eyebrow">{t("AUTOMATION SCHEDULE","خودکار شیڈول")}</span><h2 id="schedule-title">{t("Create stories automatically","خودکار طور پر کہانیاں بنائیں")}</h2><p>{t("No story becomes a video until you review its sources and approve it.","جب تک آپ مآخذ کا جائزہ لے کر منظوری نہیں دیں گے، کوئی کہانی ویڈیو نہیں بنے گی۔")}</p>
    <label className="switch-row"><div><strong>{t("Scheduled story creation","شیڈول کے مطابق کہانی بنانا")}</strong><small>{t("Research and prepare a new draft automatically","تحقیق کر کے خودکار طور پر نیا مسودہ تیار کریں")}</small></div><input type="checkbox" checked={scheduleEnabled} onChange={e=>setScheduleEnabled(e.target.checked)}/><i/></label>
    <div className="schedule-form"><label><span>{t("Frequency","تکرار")}</span><select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="Daily">{t("Daily","روزانہ")}</option><option value="Weekly">{t("Weekly","ہفتہ وار")}</option><option value="Custom days">{t("Custom days","منتخب دن")}</option></select></label><label><span>{t("Creation time","تیاری کا وقت")}</span><input type="time" value={scheduleTime} onChange={e=>setScheduleTime(e.target.value)}/></label><label className="wide"><span>{t("Timezone","ٹائم زون")}</span><select value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Asia/Dubai</option><option>Asia/Riyadh</option><option>Europe/London</option><option>America/New_York</option><option>UTC</option></select></label></div>
    {frequency!=="Daily"&&<div className="day-picker"><span>{t("Run on","ان دنوں چلائیں")}</span><div>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day,i)=><button key={day} className={days.includes(day)?"selected":""} onClick={()=>toggleDay(day)}>{language==="en"?day.slice(0,1):["پ","م","ب","ج","ج","ہ","ا"][i]}</button>)}</div></div>}
    <div className="schedule-summary"><span>◷</span><div><strong>{t("Next scheduled draft","اگلا شیڈول شدہ مسودہ")}</strong><small>{scheduleEnabled?`${frequency==="Daily"?t("Daily","روزانہ"):frequency==="Weekly"?t("Weekly","ہفتہ وار"):t("Custom days","منتخب دن")} ${t("at","،")} ${scheduleTime} · ${timezone}`:t("Scheduling is currently paused","شیڈول فی الحال روکا ہوا ہے")}</small></div></div>
    <div className="modal-actions"><button onClick={()=>setScheduleOpen(false)}>{t("Cancel","منسوخ کریں")}</button><button onClick={saveSchedule}>{t("Save schedule","شیڈول محفوظ کریں")}</button></div>
   </section></div>}
   {seoOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSeoOpen(false)}}><section className="seo-modal" role="dialog" aria-modal="true" dir={language==="ur"?"rtl":"ltr"}>
    <button className="modal-close" aria-label="Close" onClick={()=>setSeoOpen(false)}>×</button><div className="seo-heading"><span>↗</span><div><small>{language==="ur"?"یوٹیوب پبلشنگ پیک":"YOUTUBE PUBLISHING PACK"}</small><h2>{language==="ur"?"ویڈیو کی معلومات":"Video metadata"}</h2></div><i>{language==="ur"?"رجحان کا تخمینہ":"Trend estimate"}</i></div>
    <p className="trend-note">{language==="ur"?"یہ مطلوبہ الفاظ کہانی کی مناسبت اور عام سرچ پیٹرن پر مبنی ہیں۔ لائیو ٹرینڈ API منسلک ہونے پر اصل سرچ ڈیٹا استعمال ہوگا۔":"Keywords are based on story relevance and common search patterns. Live search data will be used after a trends API is connected."}</p>
    <label className="metadata-field"><span>{language==="ur"?"تجویز کردہ ویڈیو عنوان":"Recommended video title"}<b>{youtubePack.title.length}/100</b></span><div><textarea readOnly rows={2} value={youtubePack.title}/><button onClick={()=>copyText(youtubePack.title,language==="ur"?"عنوان":"Title")}>▣</button></div></label>
    <label className="metadata-field"><span>{language==="ur"?"تفصیل":"Description"}</span><div><textarea readOnly rows={6} value={youtubePack.description}/><button onClick={()=>copyText(youtubePack.description,language==="ur"?"تفصیل":"Description")}>▣</button></div></label>
    <label className="metadata-field"><span>{language==="ur"?"سرچ ٹیگز":"Search tags"}</span><div><textarea readOnly rows={3} value={youtubePack.tags}/><button onClick={()=>copyText(youtubePack.tags,language==="ur"?"ٹیگز":"Tags")}>▣</button></div></label>
    <div className="keyword-chips">{youtubePack.tags.split(", ").slice(0,5).map((tag,i)=><span key={tag}>{i<2?"↑":"◇"} {tag}</span>)}</div>
    <div className="modal-actions"><button onClick={()=>setSeoVariant(v=>v+1)}>↻ {language==="ur"?"دوسرا عنوان بنائیں":"Generate alternative"}</button><button onClick={()=>{copyText(`${youtubePack.title}\n\n${youtubePack.description}\n\n${youtubePack.tags}`,language==="ur"?"مکمل پیک":"Publishing pack");setSeoOpen(false)}}>{language==="ur"?"سب کاپی کریں":"Copy all"}</button></div>
   </section></div>}
  </section>
 </main>
}
